"""add user log

Revision ID: 07bba7d371cd
Revises: 
Create Date: 2025-07-19 22:59:58.654055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07bba7d371cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('exercise_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('CODE', 'MULTIPLE_CHOICE', 'FILE_UPLOAD', name='exercisetype'),
               nullable=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'GRADED', name='submissionstatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'GRADED', name='submissionstatus'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('exercise_type',
               existing_type=sa.Enum('CODE', 'MULTIPLE_CHOICE', 'FILE_UPLOAD', name='exercisetype'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    op.drop_table('user_log')
    # ### end Alembic commands ###
