"""Add student_code to User model

Revision ID: 0e7d61e62a60
Revises: 3aa00355bc13
Create Date: 2025-07-05 01:38:02.967994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7d61e62a60'
down_revision = '3aa00355bc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_student_code'), ['student_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_code'))
        batch_op.drop_column('student_code')

    # ### end Alembic commands ###
